
![스크린샷 2025-01-03 오전 11 47 52](https://github.com/user-attachments/assets/17391a99-78fb-4b8e-8ed0-b0bb236d34ed)

## 코루틴 중단
  - 코루틴의 실행을 일시적으로 멈추고 특정 조건이 충족될 때 다시 실행을 재개하는 기능
  - 중단은 비동기 프로그래밍에서 효율적으로 작업을 처리하기 위한 핵심 매커니즘
</br>
</br>

## 코루틴 중단의 특징
  - 코루틴은 중단되었을 때 Continuation 객체를 반환한다
  - 스레드는 저장이 불가능하고 멈추는 것만 가능하지만, 코루틴은 다른 스레드에서 시작할 수 있고, Continuation 객체는 (이론상) 직렬화와 역직렬화가 가능하며 다시 실행 될 수 있다
</br>
</br>

## 기본적인 중단을 사용하는 예제
```kotlin
suspend fun main() {
  println("before")

  suspendCorutine<Unit> { }

  println("After")
}
// before
```
- 예제를 보면 before 밖에 출력되지 않는다.
- supendCorutine 이 중단시켰기 때문이다.

</br>
</br>

## 중단을 사용하며 재개되도록 하는 예제
```kotlin
suspend fun main() {
  println("before")

  suspendCorutine<Unit> { continuation ->
    continuation.resume(Unit)
 }

  println("After")
}
// before
// After
```
- suspendCorutine은 continuation 객체를 사용할 수 있기 떄문에 이를 통해 재개하면 After가 출력된다
- suspendCorutine<Unit> 과 resume(Unit) 은 <T> 제네릭으로 반환타입을 명시하는 것이고, resume<T> 를 반환한다
- 예를 들면 suspendCorutine<String> 이면 resume("123123") 으로 반환이 가능한 것이다

</br>
</br>

## 중단을 사용하며 예외와 함께 재개되도록 하는 예제
```kotlin
class MyException: Throwable("JUST AN EXCEPTION")

suspend fun main() {
  try {
      suspendCorutine<Unit> { continuation ->
        continuation.resumeWithException(MyException())
      }
    } catch(e: MyException) {
      println("Caught!")
    }
}
// Caught!
```
- 예외가 발생했을 때 인자로 넣어준 예외를 던지는 예제
- 네트워크 예외가 발생했을 때 쓰기 좋음

